### ISSUE TITLE
command 'g++' failed with exit status 1

### ISSUE THREAD

**Issue by linfengyu77** [pkgpl/TorchWI#4]
Hi, I get the following error when installing TorchWI by command "python setup.py install".
Enviroment: python 3.7, Pytorch 1.9, CUDA Version: 11.2, gcc 7.5, System: Ubuntu 20.04.3 LTS

running install
running bdist_egg
running egg_info
writing torchwi.egg-info/PKG-INFO
writing dependency_links to torchwi.egg-info/dependency_links.txt
writing top-level names to torchwi.egg-info/top_level.txt
reading manifest file 'torchwi.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'torchwi.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'torchwi.propagator.td2d_cpu' extension
Emitting ninja build file /home/usr/FWI/TorchWI/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2.git
g++ -pthread -shared -B /usr/local/Anaconda33/compiler_compat -L/usr/local/Anaconda33/lib -Wl,-rpath=/usr/local/Anaconda33/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/usr/FWI/TorchWI/build/temp.linux-x86_64-3.7/torchwi/propagator/td2d/td2d_cpu.o /home/usr/FWI/TorchWI/build/temp.linux-x86_64-3.7/torchwi/propagator/td2d/propagator_cpu.o /home/fengw666/FWI/TorchWI/build/temp.linux-x86_64-3.7/torchwi/propagator/td2d/wrapper_cpu.o -L/usr/local/Anaconda33/lib/python3.7/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-3.7/torchwi/propagator/td2d_cpu.cpython-37m-x86_64-linux-gnu.so
g++: error: /home/usr/FWI/TorchWI/build/temp.linux-x86_64-3.7/torchwi/propagator/td2d/td2d_cpu.o: No such file or directory
g++: error: /home/usr/FWI/TorchWI/build/temp.linux-x86_64-3.7/torchwi/propagator/td2d/propagator_cpu.o: No such file or directory
g++: error: /home/usr/FWI/TorchWI/build/temp.linux-x86_64-3.7/torchwi/propagator/td2d/wrapper_cpu.o: No such file or directory
error: command 'g++' failed with exit status 1

**Comment by pkgpl** [comment]
Thank you for your interest. 
The compiler should compile the `*.cpp` files first before using the `*.o` files. 
I have no experience with the ninja build system. Try to build without ninja ([ref](https://github.com/pytorch/pytorch/issues/66896)).
`USE_NINJA=0 python setup.py install`

**Comment by linfengyu77** [comment]
Thanks. I have sloved it by altered the code (Line 61) in the setup.py: `BuildExtension` ------> `BuildExtension.with_options(use_ninja=False)`. So that the installation will avoid to use ninja to complie.
By the way, the command 'resursive-include' in MANIFEST.in seems to be 'recursive-include'.

**Comment by pkgpl** [comment]
Thank you. I fixed them.
